### ISSUE TITLE
grouping of the chords

### ISSUE THREAD

**Issue by tttp** [seancolsen/octave-compass#53]
IMO it would help to group the tetrads under their triad
- M7 7 and m7 under M
- m7 and m6 under m
Moreover, you should IMO use similar colors between the groups, eg shade of blues for the minor, share of red of the majors

I remember an interesting discussion about what at the colors of chords, but can't find it right now.

Also, you don't have the sus7 (that happens to be one chord a really like, maiden voyage... ;), if you put the other sus, please don't leave out my darling ;)

**Comment by seanmadsen** [comment]
Ahh great feedback. This stuff might be pretty easy to implement! **Questions** for you in bold.

All the chord data is here: https://github.com/seanmadsen/octave-compass/blob/master/src/Data/chords.js

(In looking at that, I just remembered that there's a bit of refactoring to do because "weight" ended up just being sequential, so I need to pull that out, as described in #56.)

The "weight" should control how the chords are ordered. **Would re-ordering the chords be sufficient for you?** Or would you like to see *more* "grouping", like with some sort of headings? The chords are ordered the same way within the polygon as they are in the "Chords in scale" list. I imagine we could add headings to the list but not within the polygon.

I really struggled with coloring the chords. **Would you be interested in submitting a PR with your desired colors?**

**What is a sus7 chord?** Is it this? https://octavecompass.com/1185 What about this https://octavecompass.com/1157 is that also a sus7? Perhaps would it be the case that one should be called `7sus4` and the other `7sus2`? I'm not familiar with these chords, so this is such a great opportunity to get input from someone like you who is!

**Comment by tttp** [comment]
Duh, the further you dig into it, the more complex it gets ;)

So keeping the two rows logic, 1st row for the triads, 2nd for the tetrads


```
    M      m      dim

  M7 7   m7 m6    dim7
```

but if the min/major/dim have colors that are related, might be enough if we are sure that on the 2nd row, we put the minors and majors next to each other?

for sus7, yes, 1185 (you stack two fourth, or if you feel like it, add a 9 to stack 3).

More generally, I'm not sure how/where to put the sus chords: it's not fitting in the "standard" minor/major harmonic, IMO, it's more a trick to replace the standard major or minor by something more ambiguous.

btw, my harmonic theory comes from studying in french and was focussed on blues/jazz/modal, so
1) I might be off on some translations
2) I'm not familiar with sus2. I would "feel it" more as two 5th stacked, ie I see it as 9 instead of a 2, but I haven't encountered it while playing standards

for the color: I'm going to have a go at it, d3 has a lot of interesting work around color schemes, I'll see if I can take something out of it

**Comment by seanmadsen** [comment]
When you say "two rows logic", I think you might be assuming that chords are organized into rows based on some characteristics. 

More info about how the app works currently: 

* The "Chords in scale" chord choices are just in a list. The *order* or the chords *is* intentional, but there are no "rows" programmed into the app. I'm using flexbox to lay out those chord choices, so they just wrap around to fit the window accordingly. If you make your window square, things get really funky!
* The order of the chords is controlled by the "weight" property here https://github.com/seanmadsen/octave-compass/blob/master/src/Data/chords.js and I set up the vales to order it by (a) number of notes, and (b) consonance (subjectively speaking). I'm open to better approaches here!
* Those chord choices only show chords that are *in* the scale. For example, a Major Scale has no augmented chords, so you won't see "augmented" as a choice. But a [https://octavecompass.com/1459](Phrygian Dominant Scale) *does* have "augmented" and "augmented 7", so now those chords are available for the user to choose. 
* Another complication is that most chords have the same name regardless of the inversion. So https://octavecompass.com/145 https://octavecompass.com/265 and https://octavecompass.com/545 would all be considered "major" chords. But some other chords have different names which depend somewhat on context or inversion or just personal preference. So you could call this https://octavecompass.com/657 a "C major 6th chord" or you could call it "the first inversion of an A minor 7th chord". I wrestled with this complexity a bit and decided that, for the sake of simplicity, I would not support chords with multiple names like this. So in creating the data for the chords I just chose the option that seemed more prevalent. 
* Another complication is non-octave-repeating chords like 9th chords (where the 9th really does need to be an octave higher and can't be considered a 2nd). Chords like that really just can't be represented by this app. As well, there are non-octave-repeating scales too, and I'm not planning to attempt to represent those in any way here. 

I'm still not quite sure *exactly* what to do about the sus7 chord(s). Are you able to make a more specific recommendation, with the above limitations in mind?

**Comment by tttp** [comment]
aah, it was completely by chance then than triads are on the first row on my screen then.

yeah, I would skip as well chord inversions.

Not sure either about sus7, let's jam on maiden voyage is my best offer right now ;)

**Comment by seancolsen** [comment]
I just finished a bunch of improvements to this app, which I hope will address this issue. If not, please feel free to comment here with a specific suggestion :slightly_smiling_face:
